/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b8dd37724aa465c89756853a2c3c1c24)
interface __BaseEnv_Env {
	RULEBOOKS: R2Bucket;
	DB: D1Database;
	RULES_IDX: VectorizeIndex;
	AI: Ai;
	RulesAgent: DurableObjectNamespace<import("./src/server/index").RulesAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "RulesAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
