/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 364e057a56b997527a2da3276ca083e5)
interface __BaseEnv_Env {
	RULEBOOKS: R2Bucket;
	DB: D1Database;
	RULES_IDX: VectorizeIndex;
	IP_LIMITER: RateLimit;
	MSG_LIMITER: RateLimit;
	AI: Ai;
	RulesAgent: DurableObjectNamespace<import("./src/server/index").RulesAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "RulesAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
