/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: a005d382a22d5bcd772c469ff87f1288)
interface __BaseEnv_Env {
	RULEBOOKS: R2Bucket;
	DB: D1Database;
	RULES_IDX: VectorizeIndex;
	IP_LIMITER: RateLimit;
	MSG_LIMITER: RateLimit;
	TTS_LIMITER: RateLimit;
	AI: Ai;
	ELEVENLABS_API_KEY: string;
	RulesAgent: DurableObjectNamespace<import("./src/server/index").RulesAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "RulesAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ELEVENLABS_API_KEY">> {}
}
